### PR TITLE
Configure test environment for Graphql Subscription

### PR DESCRIPTION
**Pull request by smallbee3**
## WHY

- Configure test environment for Graphql Subscription
<br />

## TEST PLAN

`yarn  test` will implement test code ''Resolver - user Subscription'' in tests/user.test.ts

<br />

## ISSUES

~I need to use 'User' model type in tests/user.test.ts. But I couldn't import the type from generated/nexus.ts, which was possible in 'hackatalk-server' through '/generated/graphql.ts'.
Because of the problem above, I disabled eslint to go through the error of 'better written in dot notation'.
Do you know any workaround?~

<br />

## Checklist

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk-mobile/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test`.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by smallbee3** [comment]
Yep, I rebased and updated the PR.
But it seems it is under the target 93% coverage now. haha
I better write more tests for other Subscription as well.

And could you make a comment for the ISSUE that I mentioned in the description of PR?

**Comment by smallbee3** [comment]
`clientSetup.ts` is for configuring Subscription Client in the backend's test code.

If that is the case, I better do further work to see if I could make this code(clientSetup.ts) simpler.

**Comment by smallbee3** [comment]
I've looked around other subscription test samples and found out that `clientSetup.ts` is a configuration for the testing in various environments.

For example, clientSetup.ts could be shortened and included in testSetup.ts like this.

```typescript
...
import ApolloClient from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import NodeWebSocket from 'ws';
import { SubscriptionClient } from 'subscriptions-transport-ws';
import { WebSocketLink } from 'apollo-link-ws';

let networkInterface;
export let apolloClient;
export const testHost = `http://localhost:${port}/graphql`;
const testSubscriptionHost = `ws://localhost:${port}/graphql`;

beforeAll(async (done) => {
  ...

  networkInterface = new SubscriptionClient(
    testSubscriptionHost,
    { reconnect: true },
    NodeWebSocket,
  );
  apolloClient = new ApolloClient({
    link: new WebSocketLink(networkInterface),
    cache: new InMemoryCache(),
  });

  ...
});

afterAll(async () => {
  await prisma.raw('DROP schema test CASCADE');
  networkInterface.close();
  server.close();
});
```

As you can see, only 10 lines of code replace `clientSetup.ts`
But, there could be a problem if `testSubscriptionHost` is not `ws://localhost:${port}/graphql` but something like `ws://localhost:${port}/subscrption`. 
With some example of graphql subscription test code, they were using `subscription` as its subscription path.
And in that case, `clientSetup.ts` would find out what is a proper subscription path and take that dynamically. (`clientSetup.ts` also figure out 'localhost' is baseURL of our project.)

Meanwhile, `clientSetup` is too lengthy and not easy to understand. And also, I had to add 'ignore' option to codecov.yml as it shouldn't be covered by codecov.

```yaml
ignore:
  - "tests/setup/*Setup.ts"
```

@hyochan 
Which one do you think we should choose?
The shorten configuration in testSetup.ts as above or whole `clientSetup.ts` code?


ps. Sorry for the late update. It looked a long time to analyze `clientSetup.ts`

**Comment by smallbee3** [comment]
How about choosing the short version that I mentioned before instead of `clientSetup.ts`?
And if any problem occurred because of the dynamic environment settings like the dynamic graphql subscription path or baseURL, we can go back to `clientSetup.ts`.

```typescript
export const testHost = `http://localhost:${port}/graphql`;
```

In addition, `testHost` value in testSetup.ts is already static as above. So, with `cilentSetup.ts`, we would be getting too ahead, I think.

Do you want me to update PR with the brief version?

**Comment by hyochan** [comment]
Honestly I don't 100 percent understand your point. I will leave this up to you for now and follow your decision.

**Comment by smallbee3** [comment]
Ok, I finally update the PR with bride configuration code instead of `clientSetup.ts`.

Thanks for your comments and help!

**Comment by hyochan** [comment]
@smallbee3 Could you kindly apply these changes to `ts-apollo-sequelize` and `hackalk-server`?

**Comment by smallbee3** [comment]
@hyochan 
Sure, no problem.
Shortly after, I will apply the same subscription configuration and the test code to those projects too.

By the way, thanks for your high praise!

**Pull request merged**
